// This file was generated by the 'populate-firebase.js' script.
// Any changes made to this file may be overwritten.

import { initializeApp } from 'firebase/app'

export const app = initializeApp({
  apiKey: '<your-api-key>',
  authDomain: '<your-project-id>.firebaseapp.com',
  projectId: '<your-project-id>',
  storageBucket: '<your-project-id>.appspot.com',
  messagingSenderId: '<your-sender-id>',
  appId: '<your-app-id>',
})
