// This file was generated by the 'populate-firebase.js' script.
// Any changes made to this file may be overwritten.

import { OAuthProvider } from 'firebase/auth'

export const authProvider = new OAuthProvider('microsoft.com')
authProvider.setCustomParameters({
  tenant: '00000000-0000-0000-0000-000000000000',
})
